### ISSUE TITLE
installation / debugging

### ISSUE THREAD

**Issue by thirschbuechler** [maoschanz/quicklists-gnome-shell-extension#1]
Hi,
tried installing, but no luck.

Used this guide to set the extensions up up (https://itsfoss.com/gnome-shell-extensions/),
but whether i enabled/disabled it in the Tweaker-Tool didn't matter.

The Gtk.RecentManager has some items to display, but it neither gets added to the Nemo nor to Nautilus file-managers (e.g. "file:///home/user/Downloads" is a valid recentmanager-item, I checked via python).

How did you debug / manually load the extension?

In metadata.json I added 3.28 as shell-version, but that didn't help either.

Or did I misunderstand what the extension does? A screenshot might help.

**Comment by maoschanz** [comment]
>How did you debug / manually load the extension?

i use this https://github.com/Maestroschan/gnome-extension-development-utility

>did I misunderstand what the extension does?

this extension has not been published on extensions.gnome.org because it's not seriously finished, and has bugs:
- Recent files are poorly handled, and only for a few apps.
- Recent files and special items (nautilus bookmarks for example) are incompatible with the Dash To Dock previews

I did that mainly for myself (literally: i didn't even do an english version) and i didn't take time to make it usable for other users (maybe i will, someday)

**Comment by thirschbuechler** [comment]
Ah thanks, maybe I'll be able to help; did something similar for unity-based Ubuntu
(https://github.com/thirschbuechler/ubuntu-recentquicklists)

**Comment by maoschanz** [comment]
i just see your message, too late i already finished...

**Comment by maoschanz** [comment]
>A screenshot might help.

i updated the readme too

**Comment by thirschbuechler** [comment]
haha, happens ;)

**Comment by maoschanz** [comment]
it now has settings and should be 100% usable for anyone, i guess i can close the issue

**Comment by thirschbuechler** [comment]
Awesome you've added that, a few directions on the installation process would really be helpful, which are not at all obvious:

https://github.com/thirschbuechler/quicklist-gnome-extension/blob/master/README.md

The thing about the foldername matching the uuid, as well as a general intro to extensions wouldn't hurt, etc. (altough i've got the supported-apps without the "overloaded" switch-case calls).

**Comment by maoschanz** [comment]
>altough i've got the supported-apps without the "overloaded" switch-case calls

yes it's what i did yesterday, a few months ago i learn about the API they call "GAppInfo" and it makes the whole process compatible with all apps which declare to support opening files. Of course this isn't perfect (for example Gedit doesn't declare to support source code files...) but it allows the extension to support dozens of apps with only 50 lines of code.

I only let the nautilus/nemo thing as a special case, and the thing for Tweaks 

btw it's compatible with the dock, but not with its thumbnail preview, if you disable previews it works fine

**Comment by maoschanz** [comment]
(fyi I didn't upload it on extensions.gnome.org because the ideal would be to integrate these features directly in the dash-to-dock code)

**Comment by thirschbuechler** [comment]
Amazing, yes! No manual fiddling around with the launchers' and mime-types for that purpose ;)

Ah, the "show open windows" function of dash-to-dock.. another thing for the readme.md ..
(and deletion of the default ubuntu-dock as root to keep it from respawning)

Yeah, where you publish your stuff is your game. Working on putting it directly there? Good luck :)
