### ISSUE TITLE
Extension crash with Gnome 3.38 (Ubuntu 20.10)

### ISSUE THREAD

**Issue by Cyrille37** [maoschanz/quicklists-gnome-shell-extension#20]
Hello
Thanks a lot for this tool.

The quicklist displayed in menu (nautilus icon on Gnome Shell dash) then disappears instantly, or after a second open.
Here is the log in syslog :
```
Jan 28 16:47:03 ubuntu gnome-shell[38897]:
Some code accessed the property 'discreteGpuAvailable' on the module 'appDisplay'.
That property was defined with 'let' or 'const' inside the module.
This was previously supported, but is not correct according to the ES6 standard.
Any symbols to be exported from a module must be defined with 'var'.
The property access will work as previously for the time being, but please fix your code anyway.
```
Cheers

**Comment by Cyrille37** [comment]
This morning, after a cold sart the extension works ! Yesterday for my bug report I was just restart Gnome (Alt+F2+r) but not close my session. So I close this issue.

**Comment by maoschanz** [comment]
it's a problem with a native GNOME Shell feature (the "run on GPU" menu item, which only exists for a few apps and hardware)
