### ISSUE TITLE
feature request: please make this compatible with "Ba Bar" gnome extension

### ISSUE THREAD

**Issue by pickybl2020** [maoschanz/quicklists-gnome-shell-extension#21]
"Ba Bar" can be found here
https://extensions.gnome.org/extension/4000/babar/

**Comment by maoschanz** [comment]
what i currently support is the default menus on the default icons. Sorry but i can't reimplement the extension for each single alternative windows list that builds their own menus, that's not realistic at all.

And i'll not take contributions on this topic, as i can't maintain cluttered code designed for a minor compatibility problem with other extensions i don't even know about
